### ISSUE TITLE
Report Bug

### ISSUE THREAD

**Issue by 11Carol02** [MicrosoftDocs/msteams-docs#13107]
### Type of issue

Feature doesn't work (bug)

### Feedback

Pop-up spacing issue: 
The empty space in the end of the popup cannot be controlled, Raising an issue for the same

![Image](https://github.com/user-attachments/assets/b0580d10-1fdb-46a5-a5d4-13f55977911d)

The space reduces as the content increases, and we have no control over it. 

![Image](https://github.com/user-attachments/assets/2ac739f3-1ae0-4345-8f70-397be6f2c330)

In the code, we have control over the whole pop-up's width and height and not the padding of the contents inside the pop-up, how can this be resolved?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=csharp

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md

### Author

@surbhigupta

### Document Id

b1ebd031-c5cd-ffeb-d9b2-d752511900db

### Platform Id

4f8ff019-d555-8916-4015-901d9b6eaeef

**Comment by Prasad-MSFT** [comment]
When working with pop-ups or modals in web apps, including Teams apps: the modal’s container size is set, but the content inside may not fill the space, resulting in extra empty space at the bottom. This happens because the modal’s height is fixed or set to a percentage, but the content does not always fill it.

If you set a fixed height on the pop-up, try switching to `min-height` or let the height be determined by the content, unless you need a fixed size for design reasons.

**Comment by 11Carol02** [comment]
I had set my height to "auto" so it could adjust with the contents in it. But it still has the empty space below. So, is there any other way?

**Comment by Prasad-MSFT** [comment]
Use CSS Flexbox to control how content fills the modal, avoid unnecessary fixed heights, and override default padding/margin.

**Comment by 11Carol02** [comment]
You mean I have to specify the height ? like fix height as "200px" or something? 
tried that but we are still getting the space below.
If there is any document that supports this can you please send it? thanks!

**Comment by 11Carol02** [comment]
And since the text in the pop-up is dynamic, I cannot set it to a particular height. One more issue is the pop-up doesn't render when I fix the height in Iphone, It is not consistent throughout the platforms.

**Comment by 11Carol02** [comment]
This is how it looks if i specify the width and height 

<img width="1512" height="956" alt="Image" src="https://github.com/user-attachments/assets/37662631-cb0a-4da6-94ab-ada0fbb70ac8" />

**Comment by 11Carol02** [comment]
You can see from the above pictures, the width and height is different.

**Comment by Prasad-MSFT** [comment]
According to latest update from engineering team, this is not a bug. It's by design. We control fix height of dialog, while the inner content needs to adapt to it.
