### ISSUE TITLE
Unexpected response when posting data to Microsoft Teams webhook URL

### ISSUE THREAD

**Issue by yashaswinoonela** [MicrosoftDocs/msteams-docs#7830]
I’m receiving this response when posting data to MS Teams webhook:

{"version":"1.1","content":{"headers":[{"key":"Content-Type","value":["text/plain; charset=utf-8"]}]},"statusCode":200,"reasonPhrase":"OK","headers":[],"trailingHeaders":[],"requestMessage":null,"isSuccessStatusCode":true}

when sending a request via postman or via the curl command when I expect a response of '1'. I also get this same response regardless of what headers I use. Has the way to use these webhooks changed?

Additional Note: My team has a service that uses these webhooks regularly, and they all stopped working after 03/01/2023 (around 5PM IST).

**Comment by Nivedipa-MSFT** [comment]
@yashaswinoonela - Thanks for reporting your issue. We will test this and let you know the updates.

**Comment by ankit30061990** [comment]
Yes even i am facing the same issue and getting the same response.
TeamsWebhookException: {"version":"1.1","content":{"headers":[{"key":"Content-Type","value":["text/plain; charset=utf-8"]}]},"statusCode":200,"reasonPhrase":"OK","headers":[],"trailingHeaders":[],"requestMessage":null,"isSuccessStatusCode":true}

**Comment by Deepaksai1919** [comment]
I am also receiving similar response instead of 1. 
![image](https://user-images.githubusercontent.com/31119831/210530805-bdf12643-a1a6-44df-a529-fe9cc59fbc1b.png)
However, I am getting the notification in the teams channel.
![image](https://user-images.githubusercontent.com/31119831/210530988-3d6daeda-814b-4e18-8edf-6575f50cd18e.png)

**Comment by Nivedipa-MSFT** [comment]
@Deepaksai1919 - Could you please share your webhook URL to test at our end?

**Comment by Deepaksai1919** [comment]
@Nivedipa-MSFT , the webhook is in the same format used by you. I have created a new webhook as well just now and used it to send a notification. The response is the same.

**Comment by Nivedipa-MSFT** [comment]
@Deepaksai1919 - We have tested this on Postman version 10.5.3

![image](https://user-images.githubusercontent.com/92150070/210550923-b715ef5b-8467-42b0-817f-507f646b3d28.png)

Are you using same or higher version of Postman?
Also, could you please share any additional configuration settings you have done in Postman, it will help us to repro the issue?

**Comment by Deepaksai1919** [comment]
@Nivedipa-MSFT, I don't think it is an issue with postman. I get same response using cUrl
![image](https://user-images.githubusercontent.com/31119831/210560442-f4c88a83-d425-49e5-93b2-7fe211092b01.png)
Even with python, I get the same response
![image](https://user-images.githubusercontent.com/31119831/210560629-23302275-38df-4e3f-8cc3-8fbc80ad9d3e.png)

**Comment by Deepaksai1919** [comment]
@Nivedipa-MSFT , I noticed something interesting. When there is no payload, the response status code is 200. But in  the response body, I'm getting status code as 400.

![image](https://user-images.githubusercontent.com/31119831/210563408-371ffaf4-15e3-4f8a-af97-b33f7df78bdd.png)

**Comment by yashaswinoonela** [comment]
@Nivedipa-MSFT Yes, im still getting this responce, Instead of 1.

{"version":"1.1","content":{"headers":[{"key":"Content-Type","value":["text/plain; charset=utf-8"]}]},"statusCode":200,"reasonPhrase":"OK","headers":[],"trailingHeaders":[],"requestMessage":null,"isSuccessStatusCode":true}

Note: I have a service which is using this webhook URL for more than a year now, i suddenly started seeing this issues from yesterday. Was there any new MS Teams update pushed to production?

I have also reached out to MS 365 office support team  by raising a professional ticket. But they are reciving response as 1 in there testing environment. Not sure where this descripency is.

**Comment by Nivedipa-MSFT** [comment]
@yashaswinoonela - As we have tested this via Postman and Curl but not able repro this issue. We are getting always 1 as response. We are checking this with engineering team. We will let you know once we get any updates from them.

**Comment by Nivedipa-MSFT** [comment]
@yashaswinoonela - We got an update from engineering team saying that due to undergoing migration the changes in response are expected.

**Comment by yashaswinoonela** [comment]
@Nivedipa-MSFT  So, going forward will POST request to webook will always respond with JSON responce? Or Will that be reverted back to 1 post migration activity is completed?

**Comment by Nivedipa-MSFT** [comment]
@yashaswinoonela - We have raised a bug for this. We will let you know after confirming with engineering team if it will always respond with JSON or revert back to 1.

**Comment by ankit30061990** [comment]
@Nivedipa-MSFT Any update on this?

**Comment by ChetanSharma-msft** [comment]
Hello @yashaswinoonela, @ankit30061990 - We will check the updates with engineering team and let you know the updates.

**Comment by HStoneCreek** [comment]
Same issue here! Also using a Webhook which suddenly return null.

**Comment by ChetanSharma-msft** [comment]
Hello @HStoneCreek - Sorry for the inconvenience.

We will check and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
We are actively checking the updates on this issue with engineering team and let you know as soon as possible.

**Comment by twinter-amosfivesix** [comment]
Having the same issue. To add some info to the discussion, this kind of thing has apparently happened before. Here is a post from someone experiencing the issue on 10/31/2022: https://techcommunity.microsoft.com/t5/teams-developer/message-sent-via-teams-incoming-webhooks-isn-t-showing-in-the/m-p/3666937

**Comment by SolomonHD** [comment]
👀 having the same issue as well, our last working webhook was 12/21/2022 at 3:41PM Eastern Time

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
We are actively checking the updates on this issue with engineering team and let you know as soon as possible.

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
We are actively checking the updates on this issue with engineering team and let you know as soon as possible.

Thanks!!

**Comment by Nivedipa-MSFT** [comment]
@yashaswinoonela - Deployment of the fix has completed. Could you please test and confirm on this?

**Comment by gabrielpedepera** [comment]
@Nivedipa-MSFT regarding my case: https://github.com/MicrosoftDocs/msteams-docs/issues/7830#issuecomment-1380415524

The response has changed. Now I'm getting a `400 - Bad Request` which it seems honest instead of the response inside body.

But, I still don't know what is missing. I'm using `Github Enterprise` connector to receive hooks from Pull Requests. It's not a custom integration made by myself.

This is the response:
```
Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
```

If you need more information about it. I can provide as well.

**Comment by Nivedipa-MSFT** [comment]
@gabrielpedepera - We got an update from engineering team that issue has fixed for GitHub connector. It will roll out shortly. We will inform you once it gets rollout publicly.

**Comment by Nivedipa-MSFT** [comment]
@gabrielpedepera - We are actively checking the status of fix rollout with the engineering team. We will let you know once we get any updates from them.

**Comment by Nivedipa-MSFT** [comment]
@gabrielpedepera - We got an update from engineering team saying that the fix for GitHub connector issue is rolled out publicly. Could you please test and confirm?

**Comment by gabrielpedepera** [comment]
Hi @Nivedipa-MSFT , I can confirm that the issue was resolved, and I'm already receiving the notifications again. Thank you all for the support.

**Comment by Nivedipa-MSFT** [comment]
@gabrielpedepera - Glad to hear that your issue is resolved. Could you please share your valuable [feedback](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FDevSupportFeedback&data=05%7C01%7Cv-nivedipasu%40microsoft.com%7C9e54668e251e4a07836408dafd15543b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638100565481532521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000%7C%7C%7C&sdata=2R2CdxD4cQagp%2FLkUcvuGm%2FvPVmCzpO3NEODdI%2FjThk%3D&reserved=0) here.

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
Hope this issue is resolved for everyone.

Could you please confirm so that we can close this issue from our end?

**Comment by SolomonHD** [comment]
Things still aren't working for me @ChetanSharma-msft I will conduct some more tests.

**Comment by SolomonHD** [comment]
@ChetanSharma-msft @Nivedipa-MSFT GHE Connector is working on our university's Teams again! Thanks for the help getting this resolved!! 👍🏾

**Comment by ChetanSharma-msft** [comment]
@SolomonHD - Please share your valuable feedback here: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u

**Comment by os11k** [comment]
I'm still experiencing similar issue, I can send notification from curl in bash script, but not from grafana. In grafana I'm getting:

```
Failed to send test alert.: the receiver timed out: send notification to Teams: Post
"https://zzzz/webhookb2/xxxx/IncominqWebhook/yyy/zzzz": context deadline exceeded
```

**Comment by Nivedipa-MSFT** [comment]
@os11k - We will check this with engineering team and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@os11k - Could you please share request header and response to investigate further?

**Comment by Nivedipa-MSFT** [comment]
@os11k - Could you please share request header and response to investigate further?

**Comment by os11k** [comment]
> @os11k - Could you please share request header and response to investigate further?

Hi, I'm very sorry for this noise, but issue was on my side.... So everything working as expected...
