### ISSUE TITLE
Rendering issues with Adaptive Cards in Channels 2.0

### ISSUE THREAD

**Issue by srikanth2042** [MicrosoftDocs/msteams-docs#8091]
With the introduction of Channels 2.0, the rending of Adaptive Cards is going for a toss. We observed the following major issues:

- We see weird image/object even though we don't have any image specified in our input JSON(please see below screen shot)
- Adaptive Cards are getting collapsed. The reason we chose adaptive cards over normal cards is they won't get collapsed in Channels 1.0, which now defeats the purpose.
![image](https://user-images.githubusercontent.com/33093586/218992487-a93905a4-33ec-4cad-b9ef-d975380ec49c.png)

Please fix these bugs

**Comment by Nivedipa-MSFT** [comment]
@srikanth2042 - Thanks for reporting your issue. Could you please share your adaptive card Json to test at our end?

**Comment by srikanth2042** [comment]
@Nivedipa-MSFT here is the json input:
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "msTeams": {
        "width": "full"
    },
    "body": [
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "Cardscanhaveactionsetsinthemiddleoftheirbody."
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ShowCard",
                    "title": "ShowCard",
                    "card": {
                        "type": "AdaptiveCard",
                        "body": [
                            {
                                "type": "TextBlock",
                                "text": "Thisisashowcard"
                            }
                        ]
                    }
                },
                {
                    "type": "Action.OpenUrl",
                    "title": "OpenUrl",
                    "url": "https://adaptivecards.io"
                }
            ]
        },
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "Therearealsostill\"actions\"atthebottomofthecard"
        }
    ],
    "actions": [
        {
            "type": "Action.ShowCard",
            "title": "ShowCard",
            "card": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Thisisashowcard"
                    }
                ]
            }
        },
        {
            "type": "Action.OpenUrl",
            "title": "OpenUrl",
            "url": "https://adaptivecards.io"
        }
    ]
}
```

And rendered adaptive card in Channels 2.0 mode:
![image](https://user-images.githubusercontent.com/33093586/219010268-a276a363-9acd-4838-b5b2-d4366046c175.png)

VS

Normal Teams(Channels 1.0) mode:
![image](https://user-images.githubusercontent.com/33093586/219010781-5eb590f9-04cf-48f8-88ef-e0f58346433f.png)

**Comment by Nivedipa-MSFT** [comment]
@srikanth2042 - We will test this and update you soon.

**Comment by srikanth2042** [comment]
@Nivedipa-MSFT though you can't reproduce the weird image issue, I still feel cards getting collapsed automatically is an issue. The reason we chose Adaptive Cards over normal cards is that they won't be collapsed even though they have a huge amount of data to be displayed. Can this issue be fixed to make the look and feel is consistent across Channels 1.0 & 2.0?

**Comment by Nivedipa-MSFT** [comment]
@srikanth2042 - We have raised a bug for the collapsed adaptive card. We will let you know once we get any updates on it.

**Comment by srikanth2042** [comment]
@Nivedipa-MSFT any update here?

**Comment by Nivedipa-MSFT** [comment]
@srikanth2042 - We are checking the status of the bug with engineering team. We will update you soon.

**Comment by tomabg** [comment]
any news? in the meantime the 2.0 is live but no correction seems available!?

**Comment by Nivedipa-MSFT** [comment]
@tomabg - Currently, we do not have any ETA to share. However, we want to assure you that the engineering team is actively working on resolving the bug. We understand the importance of this issue and the impact it has on your experience. Please rest assured that we will keep you informed and provide updates as soon as we have more information available. 

Thank you for your patience and understanding in this matter.

**Comment by tomabg** [comment]
are there any news? problem still exist

**Comment by Nivedipa-MSFT** [comment]
@tomabg - We are checking the status with the engineering team, we will let you know once we get any updates on it.

**Comment by Nivedipa-MSFT** [comment]
@tomabg - Currently we don't have any ETA to share. Engineering team is working on it. We will let you know once we get any updates on it.

**Comment by lindrrow-gh** [comment]
Any news? This is still a problem and adaptive card is still being auto-collapsed.

**Comment by ChetanSharma-msft** [comment]
Hello @lindrrow-gh - Sorry for delay in response.
We are actively checking the updates with engineering team and let you know.

**Comment by z3019494** [comment]
Thanks @ChetanSharma-msft - it looks like it just got fixed!

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/60587625/75fe2fb4-ab7a-405b-89f1-cbbfcf8e8f0c)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by WilbertWalrus** [comment]
> We are closing this issue for now, please feel free to reopen it, if required.

Please re-open this.

See also: https://github.com/microsoft/AdaptiveCards/issues/8641

**Comment by Prasad-MSFT** [comment]
@z3019494 - Could you please let us know in which version you tested this and observed that its fixed as mentioned [here](https://github.com/MicrosoftDocs/msteams-docs/issues/8091#issuecomment-1835317449)?

**Comment by havedill** [comment]
I'm seeing this "see more" on my version and it sucks
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/34009509/e3bb3b87-44e3-49c8-8a78-b18cb2ae16d2)


![image](https://github.com/MicrosoftDocs/msteams-docs/assets/34009509/d230df6d-fc19-4e20-b5c1-6c74a6948182)


Hiding all the important information, I have to hit 'see more' on every new message

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/34009509/ae496863-1673-4f9c-bb91-dfb1b485e6c9)

**Comment by Prasad-MSFT** [comment]
@WilbertWalrus , @havedill - We checked this using New Teams (Teams 2.1), and the card is rendering properly.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/51e3c40c-063e-4ced-99fa-921845114dd3)

**Comment by srikanth2042** [comment]
Confirming that this bug still exists in our organization tenant:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/33093586/2b328e10-fc2e-42ea-b131-b7524c4c11b4)

Teams Client is running on v1.6.00.34456 (64-bit), cross checked this in teams web client too, same issue appears.

**Comment by havedill** [comment]
Yeah i still see it on both the web version and in my clients. I check for updates daily.

Teams WEB:
![4A250C80-0944-4E21-8300-2E4FB34CD124_4_5005_c](https://github.com/MicrosoftDocs/msteams-docs/assets/34009509/813fce1b-9158-43f2-9984-41630b345b9d)

MAC Client:
![54AF08A1-3B31-45D8-8830-AEA062A439F4_4_5005_c](https://github.com/MicrosoftDocs/msteams-docs/assets/34009509/e3949ee2-988d-459e-8dd0-d08ef8b77fb8)

**Comment by z3019494** [comment]
> Yeah i still see it on both the web version and in my clients. I check for updates daily.
> 
> Teams WEB: ![4A250C80-0944-4E21-8300-2E4FB34CD124_4_5005_c](https://private-user-images.githubusercontent.com/34009509/292282237-813fce1b-9158-43f2-9984-41630b345b9d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzODA0MzEsIm5iZiI6MTcwMzM4MDEzMSwicGF0aCI6Ii8zNDAwOTUwOS8yOTIyODIyMzctODEzZmNlMWItOTE1OC00M2YyLTk5ODQtNDE2MzBiMzQ1YjlkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQwMTA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODNjMmFhOTM5YTgzMzhjMDQxZGExNWM1OTNjMjYyM2U2ZTUwMjFjOGE2YmE1NTc0NWI4NjgyZmU3YTVjOTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QqpgJhRZc_jIGrtWx3QAW6FiL4bIUMe7QhjgHRUvFls)
> 
> MAC Client: ![54AF08A1-3B31-45D8-8830-AEA062A439F4_4_5005_c](https://private-user-images.githubusercontent.com/34009509/292282241-e3949ee2-988d-459e-8dd0-d08ef8b77fb8.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzODA0MzEsIm5iZiI6MTcwMzM4MDEzMSwicGF0aCI6Ii8zNDAwOTUwOS8yOTIyODIyNDEtZTM5NDllZTItOTg4ZC00NTllLThkZDAtZDA4ZWY4Yjc3ZmI4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNFQwMTA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTMyZjBiZDZmYjA2YjU1Mjk0MDBlY2M2MmYzMjBmODBkOWY5MDgyY2I1YjYxZGQ4NmNhYWIxN2IwMTg2MDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8FhEIUsj-FwPlJnbgyz4qOQixfeBpSCeCZx3JQZ4Kpk)

Has your tenant received Loop Components in Channels yet? 

Mine was fixed the minute that some users were able to use loop components in channels.

**Comment by havedill** [comment]
Yes, we have loop components in channels
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/34009509/dd86f656-58ee-4b25-8e93-f920e0989faa)

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
We have just now tested the above provided JSON with Developer Portal quickly and Adaptive Card is displaying properly in Teams Web clients (Classic/New/Channel2.0).
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/59052547/5aaa2e6c-1ec6-4b32-a161-aebbde5e6bcc)

So, we are not able to repro your issue.
Could you please verify it once again and let us know.

**Comment by havedill** [comment]
Yes this is still an issue on all my platforms. 

Potentially this will help. Here is the exact javascript that Zabbix runs for the Teams media type, (keep in mind this is impacting other applications using webhooks like Jira as well.

https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/media/msteams?at=release/5.0


```
var SEVERITY_COLORS = [
    '#97AAB3', // Not classified.
    '#7499FF', // Information.
    '#FFC859', // Warning.
    '#FFA059', // Average.
    '#E97659', // High.
    '#E45959', // Disaster.
    '#009900', // Resolved.
    '#000000'  // Default.
];

try {
    var params = JSON.parse(value);

    if (!params.teams_endpoint) {
        throw 'Cannot get teams_endpoint';
    }
    else if (!params.teams_endpoint.includes('office.com/webhook')) {
        throw 'Invalid MS Teams webhook URL: ' + params.teams_endpoint;
    }

    params.zabbix_url = (params.zabbix_url.endsWith('/'))
        ? params.zabbix_url.slice(0, -1) : params.zabbix_url;

    if ([0, 1, 2, 3].indexOf(parseInt(params.event_source)) === -1) {
        throw 'Incorrect "event_source" parameter given: "' + params.event_source + '".\nMust be 0-3.';
    }

    // Set "use_default_message" to true for non trigger-based events.
    if (params.event_source !== '0') {
        params.use_default_message = 'true';
    }

    // Check {EVENT.VALUE} for trigger-based and internal events.
    if (params.event_value !== '0' && params.event_value !== '1'
        && (params.event_source === '0' || params.event_source === '3')) {
        throw 'Incorrect "event_value" parameter given: "' + params.event_value + '".\nMust be 0 or 1.';
    }

    // Check {EVENT.UPDATE.STATUS} only for trigger-based events.
    if (params.event_update_status !== '0' && params.event_update_status !== '1' && params.event_source === '0') {
        throw 'Incorrect "event_update_status" parameter given: "' + params.event_update_status + '".\nMust be 0 or 1.';
    }

    if (params.event_value == 0) {
        params.event_nseverity = '6';
    }

    if (!SEVERITY_COLORS[params.event_nseverity]) {
        params.event_nseverity = '7';
    }

    var request = new CurlHttpRequest(),
        facts = [],
        body = {
            themeColor: SEVERITY_COLORS[params.event_nseverity].replace('#', ''),
            summary: 'Zabbix',
            sections: [
                {
                    markdown: 'false',
                    activityTitle: params.alert_subject,
                    activitySubtitle: 'On ' + params.host_name + ' [' + params.host_ip + ']',
                    text: (params.use_default_message.toLowerCase() == 'true')
                        ? params.alert_message
                        : params.trigger_description
                }
            ],
            potentialAction: [
                {
                    '@type': 'OpenUri',
                    name: (params.event_source === '0' && params.event_recovery_value !== '0')
                        ? 'Acknowledge'
                        : 'View Event History',
                    targets: [
                        {
                            os: 'default',
                            uri: (params.event_source === '0' && params.event_recovery_value !== '0')
                                ? params.zabbix_url + '/zabbix.php?action=popup&popup_action=acknowledge.edit&eventids%5B%5D=' +
                                  params.event_id
                                : params.zabbix_url + '/tr_events.php?triggerid=' + params.trigger_id + '&eventid=' + params.event_id
                        }
                    ]
                }
            ]
        };

    if (params.use_default_message.toLowerCase() !== 'true') {
        // Problem message.
        if (params.event_value === '1' && params.event_update_status === '0') {
            facts.push({
                name: 'Event time',
                value: params.event_time + ' ' + params.event_date
            });
        }
        // Update message.
        else if (params.event_update_status === '1') {
            body.sections[0].text = params.event_update_user + ' ' + params.event_update_action + '.';

            if (params.event_update_message) {
                body.sections[0].text += '<br>Message:<br>' + params.event_update_message;
            }

            facts.push({
                name: 'Event update time',
                value: params.event_update_time + ' ' + params.event_update_date
            });
        }
        // Resolved message.
        else {
            facts.push({
                name: 'Recovery time',
                value: params.event_recovery_time + ' ' + params.event_recovery_date
            });
        }

        if (params.event_severity && params.event_severity !== '{EVENT.SEVERITY}') {
            facts.push({
                name: 'Severity',
                value: params.event_severity
            });
        }


        if (params.event_opdata && params.event_opdata !== '{EVENT.OPDATA}') {
            facts.push({
                name: 'Operational data',
                value: params.event_opdata.replace(/(?:\r\n|\r|\n)/g, '<br>')
            });
        }

        if (params.event_tags && params.event_tags !== '{EVENT.TAGS}') {
            facts.push({
                name: 'Event tags',
                value: params.event_tags
            });
        }

        Object.keys(params)
            .forEach(function (key) {
                if (key.startsWith('fact_') && params[key] !== '') {
                    facts.push({
                        name: key.substring(5),
                        value: params[key]
                    });
                }
                else if (key.startsWith('openUri_') && params[key] !== '' && !params[key].startsWith('{')) {
                    body.potentialAction.push({
                        '@type': 'OpenUri',
                        name: key.substring(8),
                        targets: [
                            {
                                os: 'default',
                                uri: params[key]
                            }
                        ]
                    });
                }
            });
        body.sections[0].facts = facts;
    }

    body.sections[0].text = body.sections[0].text.replace(/(?:\r\n|\r|\n)/g, '<br>');

    request.AddHeader('Content-Type: application/json');

    if (typeof params.HTTPProxy === 'string' && params.HTTPProxy !== '') {
        request.SetProxy(params.HTTPProxy);
    }

    Zabbix.Log(4, '[ MS Teams Webhook ] JSON: ' + JSON.stringify(body));

    var response = request.Post(params.teams_endpoint, JSON.stringify(body));

    Zabbix.Log(4, '[ MS Teams Webhook ] Response: ' + response);

    if (response === '1') {
        return 'OK';
    }
    else {
        Zabbix.Log(4, '[ MS Teams Webhook ] FAILED with response: ' + response);
        throw response;
    }
}
catch (error) {
    Zabbix.Log(3, '[ MS Teams Webhook ] ERROR: ' + error);
    throw 'Sending failed: ' + error;
}
```

**Comment by havedill** [comment]
I can reproduce with this simple bash as well to my webhook connector.

JSON="{\"title\": \"${env^^} Incoming Server Updates\", \"themeColor\": \"Red\", \"text\": \"<br>
$MESSAGE
\" }"

curl -k -H "Content-Type: application/json" -d "${JSON}" "${TEAMS_URL}"

**Comment by Prasad-MSFT** [comment]
Hi @havedill - We tried below using simple bash to our webhook connector and observed below behaviour in Teams classic and New Teams as well:
`curl.exe -H "Content-Type:application/json" -d "{ '@type': 'MessageCard', '@context': 'https://schema.org/extensions', 'summary':'\uD83D\uDCAC <b>Summary test</b> on', 'themeColor': '#00FF00', 'title': '\uD83D\uDCAC <b>Sebastian commented</b> on', 'sections':[{'text': 'The actionable messages include six visible buttons on the card. Each button is defined in the potentialAction property of the message by using ActionCard actions, each with an input type, a text field, a date picker, or a multiple-choice list. Each ActionCard has an associated action, for example HttpPOST.For the HttpPOST action, the bearer token is included with the requests. This token includes the Microsoft Entra identity of the Microsoft 365 user who took the action.You can also use this JSON to create cards containing rich inputs, such as text entry, multiselect, or selecting date and time. The code that generates the card and posts it to the webhook URL can run on any hosted service. These cards are defined as part of actionable messages and are also supported in cards used in Teams bots and message extensions.'}]}" $WEBHOOKURL`

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/278ee7b3-7b44-46bc-9995-4e4fa2dfeda4)


Could you please confirm if you are observing the same or not?

**Comment by havedill** [comment]
Slightly better looking, but no still cuts off.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/34009509/b6b500eb-b111-44eb-b8e8-ba15d01e8ee5)

**Comment by Prasad-MSFT** [comment]
Thanks for confirming, we have reopened the bug which was already raised and made engineering team aware about the reoccurrence of the issue. Once we get further update, we will inform in this thread.

Thanks again!

**Comment by havedill** [comment]
I've added some more details, hopefully it helps. Thank you

**Comment by Prasad-MSFT** [comment]
The issue seems to be fixed. Please do verify.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/95293750-01fd-419b-a47a-e62d4c0b4727)

Tested with Microsoft Teams version 24183.2200.2972.8859.
The client version is 49/24053101421.

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
